{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: csi-diskplugin-packet
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  apiToken: {{ index .Values.credential.apiToken }}
  projectID: {{ index .Values.credential.projectID }}
type: Opaque
{{- end }}
