rule_files:
- ../rules/kube-kubelet.rules.yaml

evaluation_interval: 30s

tests:
- interval: 30s
  input_series:
  - series: 'up{job="kube-kubelet", type="shoot"}'
    values: '0+0x60'
  - series: 'process_open_fds{kubernetes_io_hostname="hostname", job="kube-kubelet"}'
    values: '81+0x60'
  - series: 'process_max_fds{kubernetes_io_hostname="hostname", job="kube-kubelet"}'
    values: '100+0x60'
  - series: 'kubelet_volume_stats_available_bytes{job="kube-kubelet", type="seed", persistentvolumeclaim="pvc1"}'
    values: '2+0x60'
  - series: 'kubelet_volume_stats_capacity_bytes{job="kube-kubelet", type="seed", persistentvolumeclaim="pvc1"}'
    values: '100+0x60'
  alert_rule_test:
  - eval_time: 30m
    alertname: KubeletTooManyOpenFileDescriptorsShoot
    exp_alerts:
    - exp_labels:
        job: kube-kubelet
        service: kube-kubelet-shoot
        severity: warning
        visibility: owner
        type: shoot
        kubernetes_io_hostname: hostname
      exp_annotations:
        description: 'Shoot-kubelet (hostname) is using 81% of the available file/socket descriptors. Kubelet could be under heavy load.'
        summary: 'Shoot-kubelet has too many open file descriptors.'
    - exp_labels:
        job: kube-kubelet
        service: kube-kubelet-shoot
        severity: critical
        type: shoot
        visibility: owner
        kubernetes_io_hostname: hostname
      exp_annotations:
        description: 'Shoot-kubelet (hostname) is using 81% of the available file/socket descriptors. Kubelet could be under heavy load.'
        summary: 'Shoot-kubelet has too many open file descriptors.'
  - eval_time: 30m
    alertname: KubePersistentVolumeUsageCritical
    exp_alerts:
    - exp_labels:
        job: kube-kubelet
        severity: critical
        type: seed
        visibility: operator
        persistentvolumeclaim: pvc1
      exp_annotations:
        description: The PersistentVolume claimed by pvc1 is only 2.00% free.
        summary: PersistentVolume almost full.

