---
apiVersion: admissioncontroller.config.gardener.cloud/v1alpha1
kind: AdmissionControllerConfiguration
gardenClientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
server:
  https:
    bindAddress: 0.0.0.0
    port: 2721
    tls:
      serverCertPath: dev/tls/gardener-admission-controller.crt
      serverKeyPath: dev/tls/gardener-admission-controller.key
