# Secret containing cloud provider object store credentials for Azure storage account into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate containers and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-azure
  namespace: garden
type: Opaque
data:
  storageAccountKey: base64(storage-account-key)
  storageAccountName: base64(storage-account-name)
