apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: azure
spec:
  azure:
    constraints:
      dnsProviders:
      - name: aws-route53
      - name: unmanaged
      kubernetes:
        versions:
        - 1.9.3
        - 1.8.8
      machineImages:
      - name: CoreOS
        publisher: CoreOS
        offer: CoreOS
        sku: Stable
        version: 1576.5.0
      machineTypes:
      - name: Standard_DS2_v2
        cpu: "2"
        gpu: "0"
        memory: 7Gi
      - name: Standard_DS3_v2
        cpu: "4"
        gpu: "0"
        memory: 14Gi
      - name: Standard_DS4_v2
        cpu: "8"
        gpu: "0"
        memory: 28Gi
      - name: Standard_DS5_v2
        cpu: "16"
        gpu: "0"
        memory: 56Gi
      - name: Standard_F2s
        cpu: "2"
        gpu: "0"
        memory: 4Gi
      - name: Standard_F4s
        cpu: "4"
        gpu: "0"
        memory: 8Gi
      - name: Standard_F8s
        cpu: "8"
        gpu: "0"
        memory: 16Gi
      - name: Standard_F16s
        cpu: "16"
        gpu: "0"
        memory: 32Gi
      volumeTypes:
      - name: standard
        class: standard
      - name: premium
        class: premium
    countUpdateDomains:
    - region: westeurope
      count: 5
    - region: eastus
      count: 5
    countFaultDomains:
    - region: westeurope
      count: 2
    - region: eastus
      count: 2
