---
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: vagrant
spec:
# caBundle: |
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
  vagrant:
    constraints:
      dnsProviders:
      - name: unmanaged
