---
apiVersion: v1
kind: Secret
metadata:
  name: core-vagrant
  namespace: garden-dev
  labels:
    cloudprofile.garden.sapcloud.io/name: vagrant # label is only meaningful for Gardener dashboard
type: Opaque
data:
