apiVersion: garden.sapcloud.io/v1beta1
kind: Seed
metadata:
  name: vagrant-dev
spec:
  cloud:
    profile: vagrant
    region: local
  secretRef:
    name: seed-vagrant-dev
    namespace: garden
  ingressDomain: (minikube-ip).nip.io
  networks:
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
