apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-az
  namespace: garden-dev
spec:
  cloud:
    profile: azure
    region: westeurope
    seed: azure-dev
    secretBindingRef:
      name: core-azure
    azure:
      # resourceGroup:
      #   name: mygroup
      networks:
        vnet:
          cidr: 10.250.0.0/16
        nodes: 10.250.0.0/19
        pods: 100.96.0.0/11
        services: 100.64.0.0/13
        workers: 10.250.0.0/19
      workers:
      - name: cpu-worker
        machineType: Standard_DS1_v2
        volumeType: standard
        volumeSize: 35Gi
        autoScalerMin: 2
        autoScalerMax: 2
  kubernetes:
    version: 1.9.3
  dns:
    provider: aws-route53
    domain: johndoe-az.johndoe.example.com
  backup:
    intervalInSecond: 86400
    maximum: 6
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
  addons:
    cluster-autoscaler:
      enabled: true
    heapster:
      enabled: true
    kubernetes-dashboard:
      enabled: true
    monocular:
      enabled: false
    nginx-ingress:
      enabled: true
