apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: vagrant
  namespace: garden-development
spec:
  cloud:
    profile: vagrant
    region: local
    secretBindingRef:
      name: core-vagrant
    vagrant:
      networks:
        nodes: 10.250.0.0/19
        pods: 100.96.0.0/11
        services: 100.64.0.0/13
      endpoint: localhost:3777 # endpoint service pointing to gardener-vagrant-provider
  kubernetes:
    version: 1.9.1
  dns:
    provider: unmanaged
    domain: # <minikube-ip>.nip.io
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
  addons:
    cluster-autoscaler:
      enabled: false
    heapster:
      enabled: false
    kubernetes-dashboard:
      enabled: true
    monocular:
      enabled: false
    nginx-ingress:
      enabled: false
