apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-os
  namespace: garden-dev
spec:
  cloud:
    profile: openstack
    region: europe-1
    secretBindingRef:
      name: core-openstack
    openstack:
      networks:
        # router:
        #   id: 1234
        nodes: 10.250.0.0/19
        pods: 100.96.0.0/11
        services: 100.64.0.0/13
        workers:
        - 10.250.0.0/19
      workers:
      - name: cpu-worker
        machineType: medium_2_4
        autoScalerMin: 2
        autoScalerMax: 2
      zones:
      - europe-1a
      loadBalancerProvider: haproxy
      floatingPoolName: MY-FLOATING-POOL
  kubernetes:
    version: 1.9.3
  dns:
    provider: aws-route53
    domain: johndoe-os.johndoe.example.com
  backup:
    intervalInSecond: 86400
    maximum: 6
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
  addons:
    cluster-autoscaler:
      enabled: true
    heapster:
      enabled: true
    kubernetes-dashboard:
      enabled: true
    monocular:
      enabled: false
    nginx-ingress:
      enabled: true
