apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-gcp
  namespace: garden-development
spec:
  cloud:
    profile: gcp
    region: europe-west1
    seed: gcp-dev
    secretBindingRef:
      kind: PrivateSecretBinding
      name: core-gcp
    gcp:
      networks:
        # vpc:
        #   name: my-vpc
        nodes: 10.250.0.0/19
        pods: 100.96.0.0/11
        services: 100.64.0.0/13
        workers:
        - 10.250.0.0/19
      workers:
      - name: cpu-worker
        machineType: n1-standard-4
        volumeType: pd-standard
        volumeSize: 20Gi
        autoScalerMin: 2
        autoScalerMax: 2
      zones:
      - europe-west1-b
  kubernetes:
    version: 1.9.3
  dns:
    provider: aws-route53
    domain: johndoe-gcp.johndoe.example.com
  backup:
    intervalInSecond: 86400
    maximum: 6
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
  addons:
    cluster-autoscaler:
      enabled: true
    heapster:
      enabled: true
    kubernetes-dashboard:
      enabled: true
    monocular:
      enabled: false
    nginx-ingress:
      enabled: true
