---
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-vagrant
  namespace: garden-dev
spec:
  cloud:
    profile: vagrant
    region: local
    secretBindingRef:
      name: core-vagrant
    vagrant:
      endpoint: localhost:3777 # endpoint service pointing to gardener-vagrant-provider
  kubernetes:
    version: 1.9.6
  dns:
    provider: unmanaged
    domain: <minikube-ip>.nip.io
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
  addons:
    heapster:
      enabled: true
    kubernetes-dashboard:
      enabled: true
    cluster-autoscaler:
      enabled: true
    nginx-ingress:
      enabled: true
    kube-lego:
      enabled: true
      email: john.doe@example.com
    monocular:
      enabled: false
