
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: garden.sapcloud.io:psp:kube-system:calico-kube-controllers
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.calico-kube-controllers
  resources:
  - podsecuritypolicies
  verbs:
  - use
