apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: apiserver
{{- if .Values.annotations }}
  annotations:
{{ .Values.annotations | toYaml | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.type }}
  selector:
    app: kubernetes
    role: apiserver
  ports:
  - name: kube-apiserver
    protocol: TCP
    port: 443
    targetPort: {{ .Values.targetPort }}
{{- if .Values.nodePort }}
    nodePort: {{ .Values.nodePort }}
{{- end }}
