groups:
- name: kube-pods.rules
  rules:
  - alert: KubePodsPending
    expr: kube_pod_status_phase{phase="Pending", namespace="kube-system"} == 1
    for: 10m
    labels:
      service: kube-kubelet
      severity: warning
    annotations:
      description: Pod {{ $labels.pod }} is in state Pending for more than 10 minutes
      summary: Pod is in pending state
