apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: {{ template "deploymentname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    addonmanager.kubernetes.io/mode: EnsureExists
{{ template "deploymentspec" . }}
