# Gardener API server configuration values
apiserver:
  enabled: true
  replicaCount: 1
  serviceAccountName: gardener-apiserver
  image:
    repository: rfranzke/gardener-apiserver
    tag: latest
  etcd:
    useSidecar: false # only meant for development purposes. if this is set to true, other etcd config values are ignored
    servers: https://etcd:2379
    # caBundle: |
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # tls:
    #   crt: |
    #     -----BEGIN CERTIFICATE-----
    #     ...
    #     -----END CERTIFICATE-----
    #   key: |
    #     -----BEGIN RSA PRIVATE KEY-----
    #     ...
    #     -----END RSA PRIVATE KEY-----
  groupPriorityMinimum: 10000
  versionPriority: 20
  caBundle: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  tls:
    crt: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----

# Gardener controller manager configuration values
controller:
  enabled: true
  replicaCount: 1
  serviceAccountName: gardener-controller-manager
  image:
    repository: rfranzke/gardener-controller-manager
    tag: latest
  internalDomain:
    provider: aws-route53 # currently, only aws-route53 is supported
    hostedZoneID: Z3ABCDE1FGHIJK
    domain: example.com
    credentials:
      accessKeyID: access-key-id-with-route53-privileges
      secretAccessKey: secret-access-key-with-route53-privileges
  defaultDomains: []
  # - domain: example.com
  #   provider: aws-route53 # currently, only aws-route53 is supported
  #   hostedZoneID: Z3ABCDE1FGHIJK
  #   credentials:
  #     accessKeyID: access-key-id-with-route53-privileges
  #     secretAccessKey: secret-access-key-with-route53-privileges
  alertingSMTP: []
  # - to: email-address-to-send-alerts-to
  #   from: email-address-to-send-alerts-from
  #   smarthost: smtp-host-used-for-sending
  #   auth_username: smtp-authentication-username
  #   auth_identity: smtp-authentication-username
  #   auth_password: smtp-authentication-password
  config:
    clientConnection:
      acceptContentTypes: application/json
      contentType: application/json
      qps: 100
      burst: 130
    controller:
      healthCheckPeriod: 30s
      reconciliation:
        concurrentSyncs: 20
        resyncPeriod: 10m
        retryDuration: 1440m
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: configmaps
    logLevel: info
    metrics:
      interval: 30s
    server:
      bindAddress: 0.0.0.0
      port: 2718
