kubernetesVersion: 1.13.1
replicas: 1
podAnnotations: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  hyperkube: image-repository
resources:
  requests:
    cpu: 23m
    memory: 64Mi
  limits:
    cpu: 1500m
    memory: 1500Mi