apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver-proxy-config
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    origin: gardener
data:
  proxy.conf: |-
    daemon off;
    error_log {{ .Values.errorLog }};
    stream {
        log_format basic '[client $remote_addr:$remote_port] [server $server_addr:$server_port]';
        server {
            access_log {{ .Values.accessLog }};
            listen {{ .Values.advertiseIPAddress }}:443;
            proxy_pass {{ .Values.proxySeedServer }};
            proxy_protocol on;

            proxy_protocol_timeout 5s;
            resolver_timeout 5s;
            proxy_connect_timeout 5s;
        }
    }

    events {}
