cloudConfigContent: {}
storageClassesContent: {}
coreAddonsContent: {}
optionalAddonsContent: {}

replicas: 1
podAnnotations: {}
images:
  kube-addon-manager: image-repository:image-tag
shootAPIServer:
  Capabilities:
    KubeVersion:
      GitVersion: v1.13

resources:
  requests:
    cpu: 100m
    memory: 30Mi
  limits:
    cpu: 1000m
    memory: 1000Mi

vpa:
  enabled: true