kind: Deployment
apiVersion: {{ include "deploymentversion" . }}
metadata:
  name: csi-attacher
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: csi-attacher
    garden.sapcloud.io/role: controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
      role: csi-attacher
  template:
    metadata:
{{- if .Values.podAnnotations.csiAttacher }}
      annotations:
{{ toYaml .Values.podAnnotations.csiAttacher | indent 8 }}
{{- end }}  
      labels:
        app: kubernetes
        role: csi-attacher
        garden.sapcloud.io/role: controlplane
    spec:
      containers:
        - name: csi-attacher
          image: {{ index .Values.images "csi-attacher" }}
          args:
            - "--v=5"
            - "--csi-address=csi-plugin-controller:80"
            - "--kubeconfig=/var/lib/csi-attacher/kubeconfig"
            - "--leader-election"
            - "--leader-election-namespace=kube-system"
            - "--leader-election-identity=$(MY_NAME)"
          env:
            - name: MY_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- if .Values.attacherResources }}
          resources:
{{ toYaml .Values.attacherResources | indent 12 }}
{{- end }}
          volumeMounts:
            - name: csi-attacher
              mountPath: /var/lib/csi-attacher
      volumes:
        - name: csi-attacher
          secret:
            secretName: csi-attacher