---
apiVersion: v1
kind: Secret
metadata:
  name: vpn-shoot
  namespace: kube-system
type: Opaque
data:
  ca.crt: {{ .Values.vpnShootSecretData.ca }}
  tls.crt: {{ .Values.vpnShootSecretData.tlsCrt }}
  tls.key: {{ .Values.vpnShootSecretData.tlsKey }}
