{{- if .Values.controller.enabled }}
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: gardener-controller-manager
  namespace: garden
  labels:
    app: gardener
    role: controller-manager
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: gardener
      role: controller-manager
  template:
    metadata:
      labels:
        app: gardener
        role: controller-manager
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccountName }}
      containers:
      - name: gardener-controller-manager
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
        - /gardener-controller-manager
        - --config=/etc/gardener-controller-manager/config.yaml
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.controller.config.server.port }}
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 750m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: gardener-controller-manager-config
          mountPath: /etc/gardener-controller-manager
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: gardener-controller-manager-config
        configMap:
          name: gardener-controller-manager-configmap
{{- end}}
