{{ if .Values.hvpa.enabled }}
{{- /* .Values.replicas is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.replicas | toString) "0" }}
{{- if eq .Values.role "main" }}
apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  #annotations:
    #"hpa-controller": "hvpa"
    #"enable-vertical-scale-down": "true"
  labels:
    controller-tools.k8s.io: "1.0"
  name: etcd-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleUpStabilizationWindow: {{ .Values.scaleUpStabilizationWindow }}
  scaleDownStabilizationWindow: {{ .Values.scaleDownStabilizationWindow }}
  minCpuChange:
    value: 100m
    percentage: 80
  minMemChange:
    value: 200M
    percentage: 80
  hpaTemplate:
    maxReplicas: {{ .Values.replicas }}
    minReplicas: {{ .Values.replicas }}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.targetAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.targetAverageUtilization }}
  vpaTemplate:
    resourcePolicy:
      containerPolicies:
      - containerName: etcd
        minAllowed:
          memory: 1000Mi
          cpu: 500m
        maxAllowed:
          memory: 20Gi
          cpu: 2500m
  weightBasedScalingIntervals:
    - vpaWeight: 1
      startReplicaCount: {{ .Values.replicas }}
      lastReplicaCount: {{ .Values.replicas }}
  targetRef:
    apiVersion:  {{ include "statefulsetversion" . }}
    kind: StatefulSet
    name: etcd-{{ .Values.role }}
{{ end }}
{{ end }}
{{ end }}
