apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:konnectivity-agent
  labels:
    app: konnectivity-agent
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.konnectivity-agent
  resources:
  - podsecuritypolicies
  verbs:
  - use