apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.konnectivity-agent
  labels:
    app: konnectivity-agent
spec:
  hostNetwork: true
  volumes:
  - secret
  - projected
  - emptyDir
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny