images:
  gardener-resource-manager: image-repository:image-tag

resources:
  requests:
    cpu: 23m
    memory: 47Mi
  limits:
    cpu: 400m
    memory: 512Mi

replicas: 1

controllers:
  managedResource:
    syncPeriod: 1m0s
    concurrentSyncs: 20
  managedResourceHealth:
    syncPeriod: 1m0s
    concurrentSyncs: 10

podAnnotations: {}
