global:
  podNetwork: 100.96.0.0/11
kube-proxy:
  kubeconfig: dummy-add-the-data-of-a-kubernetes-secret
  featureGates: {}
  podAnnotations: {}
  images:
    hyperkube: image-repository
kube-dns:
  clusterDNS: 100.64.0.10
  images:
    kube-dns: image-repository:image-tag
    kube-dns-dnsmasq: image-repository:image-tag
    kube-dns-sidecar: image-repository:image-tag
    kube-dns-autoscaler:  image-repository:image-tag
vpn-shoot:
  serviceNetwork: 10.0.0.0/24
  podNetwork: 192.168.0.0/16
  nodeNetwork: 172.16.0.0/20
  podAnnotations: {}
  images:
    vpn-shoot: image-repository:image-tag
calico:
  cloudProvider: aws
  images:
    calico-node: image-repository:image-tag
    calico-cni:  image-repository:image-tag
monitoring:
  node-exporter:
    images:
      node-exporter: image-repository:image-tag
