role: for-test
replicas: 1

images:
  etcd: image-repository:image-tag

storageCapacity: 16Gi

tlsServerSecretName: etcd-server-tls
tlsClientSecretName: etcd-client-tls
podAnnotations: {}
servicePorts:
  client: 2379
  server: 2380
  backuprestore: 8080

metrics: basic

scaleUpStabilization:
  duration: "5m"
  minCpuChange:
    value: "1"
    percentage: 80
  minMemChange:
    value: 2G
    percentage: 80

scaleDownStabilization:
  duration: "15m"
  minCpuChange:
    value: "1"
    percentage: 80
  minMemChange:
    value: 2G
    percentage: 80

targetAverageUtilization: 80

etcdResources:
  requests:
    cpu: 300m
    memory: 1000M
  limits:
    cpu: "4"
    memory: 30G

hvpa:
  enabled: false
