apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: coredns
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kube-dns
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
