{{- define "containerd-require-initializer" -}}
- path: /etc/systemd/system/containerd.service.d/10-require-containerd-initializer.conf
  permissions: 0644
  content:
    inline:
      encoding: ""
      data: |
        [Unit]
        After=containerd-initializer.service
        Requires=containerd-initializer.service
{{- end -}}