{{- define "gardener.secret-internal-domain" -}}
{{- if .Values.global.controller.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain-{{ ( required ".controller.internalDomain.domain is required" (replace "." "-" .Values.global.controller.internalDomain.domain) ) }}
  namespace: garden
  labels:
    app: gardener
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    garden.sapcloud.io/role: internal-domain
  annotations:
    dns.gardener.cloud/provider: {{ ( required ".controller.internalDomain.provider is required" .Values.global.controller.internalDomain.provider ) }}
    dns.gardener.cloud/domain: {{ ( required ".controller.internalDomain.domain is required" .Values.global.controller.internalDomain.domain ) }}
type: Opaque
data:
{{ toYaml .Values.global.controller.internalDomain.credentials | indent 2 }}
{{- end }}
{{- end -}}
