apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from Shoot's Kubernetes API Server to talk to pods labeled
      with 'networking.gardener.cloud/from-shoot-apiserver=allowed'.
  name: allow-from-shoot-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/from-shoot-apiserver: allowed
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kubernetes
          garden.sapcloud.io/role: controlplane
          role: apiserver
  policyTypes:
  - Ingress
  egress: []
