---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    ---
    apiVersion: {{ include "kube-scheduler.componentconfigversion" . }}
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: /var/lib/kube-scheduler/kubeconfig
    leaderElection:
      leaderElect: true
{{- if .Values.config.algorithmSource.provider }}
    algorithmSource:
      provider: {{ .Values.config.algorithmSource.provider }}
{{- end }}
