---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "rules/**").AsConfig | indent 2 }}
# provider-specific rules
{{- if .Values.extensions.rules }}
{{toString .Values.extensions.rules | indent 2}}
{{- end}}
# optional rules
{{- $files := .Files }}
{{- range $k, $v := .Values.rules.optional }}
{{- if and $v.enabled $v.rules }}
{{ ($files.Glob ( printf "optional-rules/%s.rules.yaml" $k)).AsConfig | indent 2 }}
{{- end }}
{{- end }}