apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: apiserver
spec:
  exportTo:
  - "*"
  host: {{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 5000
        tcpKeepalive:
          time: 7200s
          interval: 75s
    tls:
      mode: DISABLE
